name: Code Quality

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11] 

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Linting Tools
        run: pip install flake8 bandit

      - name: Run Flake8 
        run: flake8 . --ignore=E501,W291,W292,W293,E302,E305,F401

      - name: Run Bandit 
        run: bandit -r . --skip B104,B201